### ISSUE TITLE
[daemon] 参考nginx, 实现mirai -s SIGNAL以方便对mirai进程进行管理

### ISSUE THREAD

**Issue by ryuujo1573** [iTXTech/mirai-console-loader#105]
相关issue: #92 

## 应用场景描述

当机器人挂载于服务器时，需要使用
```sh
nohup mcl 2>&1 > path/to/logs/`date +%Y-%m-%d.log` &
```
以使其运行于后台; 
当退出服务器连接后，无法通过`fg`快速恢复`nohup`执行的后台进程，导致mirai实例的管理困难。

例如需要重置mirai进程，我需要`ps aux | grep java`并kill指定pid的方式来结束mirai进程并再次执行`nohup mcl ...`。

## 需求

能否通过类似于nginx的设计，通过形如`nginx -s stop|quit|reopen|reload`等方式，对mirai及对应java实例进行管理？

**Comment by PeratX** [comment]
建议使用pm2

**Comment by ryuujo1573** [comment]
目前已经用screen -R mirai来作为替代方案，谢谢
