### ISSUE TITLE
第一次运行报错

### ISSUE THREAD

**Issue by FXDYJ** [iTXTech/mirai-console-loader#106]
图片放图床了：https://sm.ms/image/l3FbGCPNgQHoDEW
系统版本：win11
java版本：11.0.14
MCL版本：MCL 2.0.0-beta.2

**Comment by FXDYJ** [comment]
在线等，挺急的

**Comment by PeratX** [comment]
尝试不要用中文目录呢

**Comment by PeratX** [comment]
bug已复现，已修复，下个版本会包含此修复。
现在请不要使用中文目录

**Comment by FXDYJ** [comment]
好的，继续Debug去了
