### ISSUE TITLE
[求助]文件夹生成相关问题😩

### ISSUE THREAD

**Issue by ExMikuPro** [iTXTech/mirai-console-loader#107]
为什么在macOS里运行mcl.jar之后libs和plugin等文件夹会在用户根目录下生成啊😩

**Comment by PeratX** [comment]
请提交更多信息协助我们调查

**Comment by ExMikuPro** [comment]
> ![image](https://user-images.githubusercontent.com/12100985/168040940-24c4ed02-4ccc-4465-a6ba-e8b5fc9dd613.png)
> 
> 在我的 macOS 上没有问题



> 请提交更多信息协助我们调查

**Comment by ExMikuPro** [comment]
打开终端运行 “mcl.jar”后lib文件什么的会出现在用户根目录下
<img width="697" alt="截屏2022-05-13 上午11 39 59" src="https://user-images.githubusercontent.com/72144156/168206889-d54ee359-6c6e-4582-a9bb-e00e9a7ae195.png">
<img width="1032" alt="截屏2022-05-13 上午11 40 39" src="https://user-images.githubusercontent.com/72144156/168206908-1c5a5af8-96d3-4c42-b6fa-c8335ce507ab.png">

**Comment by PeratX** [comment]
你为什么要在你个人数据目录运行呢

**Comment by ExMikuPro** [comment]
> 你为什么要在你个人数据目录运行呢



> 你为什么要在你个人数据目录运行呢

o,找到问题了，没运行在那个指定的地址，感谢感谢！
