### ISSUE TITLE
版本

### ISSUE THREAD

**Issue by itchbelief** [iTXTech/mirai-console-loader#11]
![image](https://user-images.githubusercontent.com/20786564/98089056-34e4e380-1ebd-11eb-9818-aeefa56ebc24.png)
不管怎么弄 总是下载最新的，是我README.md理解有错吗？

**Comment by dousha** [comment]
要锁定当前版本，在启动时需要加入 `-u` 参数，如：

`./mcl -u`

**Comment by itchbelief** [comment]
好的,感谢。我开始--disable-script 都没用，漏试了--disable-update
