### ISSUE TITLE
MCL 的 Module 开发是否应该改用 Java SPI 

### ISSUE THREAD

**Issue by cssxsh** [iTXTech/mirai-console-loader#112]
目前的加载方式是 指定并加载 package 下的所有类，似乎用  Java SPI  加载的方式会优雅一些？

**Comment by PeratX** [comment]
你去pr就有了？

**Comment by cssxsh** [comment]
> 你去pr就有了？

@PeratX 你 merge 太快了，我文档还没写呢（我不知道怎么 Draft）

**Comment by PeratX** [comment]
写了再pr咯
