### ISSUE TITLE
在termux环境下报错libc.so.6

### ISSUE THREAD

**Issue by shenmo7192** [iTXTech/mirai-console-loader#113]
```
Failed to load native library:jansi-2.4.0-d775ef2cf8943b0a-libjansi.so. osinfo: Linux/arm64
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-d775ef2cf8943b0a-libjansi.so: dlopen failed: library "libc.so.6" not found
```
 1.2.3-93ac7d8是最后一个支持的版本

更新的版本似乎用了原生的库，和安卓的musl不兼容

**Comment by cssxsh** [comment]
并不影响程序的运行吧

**Comment by shenmo7192** [comment]
> 并不影响程序的运行吧

在fetch announcement之前就卡死了
我是没看到announcement，具体卡在哪个部分不清楚

**Comment by PeratX** [comment]
可能是网络，-c0 打开debug调试信息
`"-Dmcl.mcl.no-ansi-console-init=ture"`关闭jansi初始化
https://github.com/iTXTech/mirai-console-loader/blob/master/cli.md#%E7%A6%81%E7%94%A8%E6%8E%A7%E5%88%B6%E5%8F%B0%E9%A2%9C%E8%89%B2
