### ISSUE TITLE
qq登录直接报错

### ISSUE THREAD

**Issue by Starmoon0** [iTXTech/mirai-console-loader#114]
更新了mcl-2.1.0，登录qq时直接报错

日志文件
[latest.log](https://github.com/iTXTech/mirai-console-loader/files/8775611/latest.log)

试了jdk11到18都不行，可否有解决方案？

**Comment by Starmoon0** [comment]
新版本放在我的服务器上也是一样的报错，好像是jar包没有签名导致，但是版本降级之后一切正常

**Comment by PeratX** [comment]
版本降级？
是否已安装bc包？

**Comment by cssxsh** [comment]
`/.mcl -a org.bouncycastle:bcprov-jdk15on`

**Comment by Starmoon0** [comment]
> `/.mcl -a org.bouncycastle:bcprov-jdk15on`
> 
> 安装bc包

你这还是用不了

java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
……
Caused by: java.util.jar.JarException: The JCE Provider file:/root/mcl/libs/mirai-core-all-2.11.0.jar is not signed.
……

**Comment by Starmoon0** [comment]
> 版本降级？ 是否已安装bc包？

兄弟，mcl版本降级到1.2.3可以用，升级到2.1.0就不行了
还是给你看一下控制台的输出吧
[console.txt](https://github.com/iTXTech/mirai-console-loader/files/8789493/console.txt)

**Comment by cssxsh** [comment]
可以使用 openjdk  避免签名问题

https://adoptium.net/

**Comment by cssxsh** [comment]
> 版本降级？ 是否已安装bc包？

我记得 bc 包 要在 mirai 之前被加载才行，有做处理吗

**Comment by PeratX** [comment]
bc包需要被加载为core类型才行
`--type core`
