### ISSUE TITLE
版本更新检查异常

### ISSUE THREAD

**Issue by 4o4E** [iTXTech/mirai-console-loader#119]
```log
  16:36:21 [INFO] Verifying "net.mamoe:mirai-console" v2.11.1
  16:36:21 [WARN] Package "net.mamoe:mirai-console" has newer version "2.11.0"
```
mcl版本2.1.0

`2.11.1`应该比`2.11.0`新

**Comment by xtyuns** [comment]
其实这种从 pkg 的 version 可以直接从 maven 中读取信息，然后通过 gitub action 自动同步到 Mirai Repo 中吧 @PeratX 

```bash
#!/bin/env bash

METADATA=`curl -sL https://maven.aliyun.com/repository/public/net/mamoe/mirai-console/maven-metadata.xml`
echo $METADATA | sed 's/\s\+/\n/g' | awk 'gsub(/\s*<\/?version>/, "")'
```

但是需要好像存在两个问题：
1. maven 中的所有版本是否都作为 stable 通道的来源
2. maven metadata 中 version 并非是按照发布顺序排列的，与 MCL 中的最新版本判定机制不兼容

**Comment by PeratX** [comment]
mcl支持maven频道，且支持版本排序，详见文档
https://github.com/iTXTech/mirai-console-loader/blob/master/cli.md#%E5%9C%A8updater%E4%B8%AD%E4%BD%BF%E7%94%A8maven%E6%9B%B4%E6%96%B0%E9%A2%91%E9%81%93

关于您说的2.11.1被降级到2.11.0是因为repo中版本未更新。
