### ISSUE TITLE
MCL以Service的方式启动

### ISSUE THREAD

**Issue by 250king** [iTXTech/mirai-console-loader#121]
因为SSH断开会话后程序会被迫退出，虽然有Screen解决方案，但它不能使得MCL能够自启动，一重启系统就不得不重新挂起，感觉比较麻烦，就想拿Service的方式来使MCL能够后台运行。
于是在`/usr/lib/systemd/system`创建`mirai.service`，内容如下
```
[Unit]
Description=mirai 是一个在全平台下运行，提供 QQ Android 协议支持的高效率机器人库
After=network.target

[Service]
Type=simple
Restart=always
ExecStart=java -jar /home/chino/temp/mcl.jar

[Install]
WantedBy=multi-user.target
```
但启动失败，而且拿`java -jar /home/chino/temp/mcl.jar`也出现一系列问题。
请问可不可以自定义工作目录？或者说作者能否在这方面有个适应`/bin/sh`环境的优化？

**Comment by 250king** [comment]
不过也有一个地方还是要提点一下，就是好像不支持正常结束线程（SIGTERM）操作
![image](https://user-images.githubusercontent.com/61256966/174596424-3d69061d-869e-485c-a35e-04a03eedf0ea.png)
其实这里应该注意一下，因为如果经常使用kill -9（SIGKILL）强制结束，对MCL里的一些插件也不是很友好，毕竟有一些插件已经定义了在退出前有一系列操作，例如数据保存之类的
而且最关键的是我执行Service stop就卡住了（以为我网卡了）

**Comment by guation** [comment]
我之前也尝试过 最后跑不起来只能继续用screen了
