### ISSUE TITLE
旧版本在升级 mirai 时处理不当导致故障

### ISSUE THREAD

**Issue by Initial-heart-1** [iTXTech/mirai-console-loader#125]
近期使用 mcl 升级 mirai（core,console） 至 2.12.0 后 mirai-api-http 出现故障（[mirai #2145](https://github.com/mamoe/mirai/issues/2145)）
按指示提供信息时发现 plugins 文件夹存在残留的 2.7.0 版本的 mirai-console
删除后故障排除
这可能给其他用户造成困扰，我所知的就有两个倒霉蛋跟我一起因为这事停机了
建议至少在公告中添加相应的提示以便用户处理该故障
不管为什么升级后加载到了这个 mirai-console，按[这里](https://github.com/mamoe/mirai/issues/2145#issuecomment-1179513607)所说提交本 issue
~~之前找错地方了尬死了~~

**Comment by PeratX** [comment]
为什么会在plugins文件夹中存在mirai -console呢？正常只会存在于libs中。
出现这种情况的唯一可能是 修改miraiconsole频道的时候错误指定了类型。

**Comment by Initial-heart-1** [comment]
> 为什么会在plugins文件夹中存在mirai -console呢？正常只会存在于libs中。 出现这种情况的唯一可能是 修改miraiconsole频道的时候错误指定了类型。

如果这是一个用户问题，无法解释其他用户报告了相同的问题
这也是为什么发起这个issue

**Comment by Initial-heart-1** [comment]
回忆了一下，唯一的一次对mcl频道进行操作是[mirai #1536](https://github.com/mamoe/mirai/issues/1536)
恰好，版本号为`2.7.0`

**Comment by guation** [comment]
我也遇到了类似问题，但是是更新后plugins出现了mirai-api-http-2.6.2.jar和mirai-api-http-2.6.2.mirai2.jar两个mirai-api-http之后就因为其中一个先加载把端口占住了第二个再加载的时候端口监听不了然后就崩了
