### ISSUE TITLE
不确定的报错

### ISSUE THREAD

**Issue by greenhandzdl** [iTXTech/mirai-console-loader#128]
![Screenshot_20220723_164044_com termux](https://user-images.githubusercontent.com/61241103/180597663-9fad205a-47a1-420a-9c27-dadc4d476870.jpg)

**Comment by PeratX** [comment]
可能是某个插件有损坏，zip不对

**Comment by Karlatemp** [comment]
使用 zip 软件一个一个打开 plugins 文件夹内的插件, 无法打开的就是错误源
