### ISSUE TITLE
自动下载插件下载的是.jar

### ISSUE THREAD

**Issue by Nambers** [iTXTech/mirai-console-loader#137]
应该改成.mirai2.jar?

**Comment by cssxsh** [comment]
我这个pr已经处理了
https://github.com/iTXTech/mirai-console-loader/issues/116
https://github.com/iTXTech/mirai-console-loader/pull/133

**Comment by Itsusinn** [comment]
现在自动下载为何又变成了jar而不是mirai2.jar?

**Comment by Itsusinn** [comment]
> 现在自动下载为何又变成了jar而不是mirai2.jar?

已探明是阿里的镜像源同步策略问题
