### ISSUE TITLE
2.1.1版本启动文件里多了一个回车符

### ISSUE THREAD

**Issue by SekiBetu** [iTXTech/mirai-console-loader#138]
/usr/bin/env: ‘sh\r’: No such file or directory

**Comment by SekiBetu** [comment]
在linux中用vim打开mcl文件后重新设置文件的格式可解决
```shell
:set ff=unix
```

**Comment by SekiBetu** [comment]
希望开发者在打包时不要使用与本仓库有出入的文件，明明仓库里的mcl文件是没问题的，怎么到了release里mcl文件就不对了

**Comment by StageGuard** [comment]
可能是我 openjdk 的问题
