### ISSUE TITLE
上传群文件问题

### ISSUE THREAD

**Issue by xiaopeng12342** [iTXTech/mirai-console-loader#141]
之前一直用的mcl-1.0.5版本，上传文件到群正常。
近期换成了mcl-2.1.1版本，上传完成后，群消息里面没有文件上传完成的提示，群文件里面也要手动刷新一下才能显示出来文件。而且比如我23：00上传的，然后过个十来分钟才去刷新，刷新出来后，显示的上传时间是刚刚。

**Comment by PeratX** [comment]
请汇报给mirai
