### ISSUE TITLE
还是文件路径的问题....

### ISSUE THREAD

**Issue by milanor1970** [iTXTech/mirai-console-loader#144]
这样，如上一个问题中提到的。我删除了目录，然后启动，它在data下生成了一个Petpet的空目录然后会提示：
`ヾ(≧▽≦*)o Petpet 初始化成功，使用 pet 以获取keyList! 无法读取文件，请检查data目录 Petpet 加载完毕 (共 0 素材，随机表列包含 0 素材，已禁用 0)`
我再次给图片资源放进去则是上一个回答的输出内容。
`Petpet GifMakerThreadPoolSize: 2
ヾ(≧▽≦*)o Petpet 初始化成功，使用 pet 以获取keyList!
无法读取 C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet/data.json:

java.io.FileNotFoundException: C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet\data.json (系统找不到指定的文件。)
Petpet 加载完毕 (共 0 素材，随机表列包含 0 素材，已禁用 0)`
因为“data.json”文件本身就不在“xmmt.dituon.petpet”路径下而是在"xmmt.dituon.petpet\pngfiles\data.json"下才对？这个提示信息显示的路径和我看到的不一样啊...所以会找不到文件出错。

**Comment by PeratX** [comment]
这个问题应该反馈给插件作者
