### ISSUE TITLE
需要协助：通过 MCL 向 Mirai 添加 -D=mirai.no-desktop JVM 参数

### ISSUE THREAD

**Issue by zbx1425** [iTXTech/mirai-console-loader#154]
我希望在 Windows 下使 Mirai 在终端输出滑动验证等信息。我尝试了以下的写法，但它们要么引起 MCL 报未知参数错误，要么引起 Mirai-Console 报未知参数错误。
```
./mcl -g -D=mirai.no-desktop
./mcl -g -Dmirai.no-desktop
./mcl -g mirai.no-desktop
./mcl -D=mirai.no-desktop
./mcl -Dmirai.no-desktop
./mcl mirai.no-desktop
```

**Comment by XieXiLin3** [comment]
经测试，使用 `java -Dmirai.no-desktop -jar mcl.jar` 即可实现。 

> 好像是快捷脚本默认将参数加在 `-jar` 后面导致的。

**Comment by cssxsh** [comment]
你编译一下 `mcl` 或者 `mcl.bat` 的内容不就好了吗
