### ISSUE TITLE
无法正常使用permission赋权

### ISSUE THREAD

**Issue by Shanshui2022** [iTXTech/mirai-console-loader#155]
在更新了MCL2.1.2版本以后，赋权功能失效，控制台内输入
> /permission *:* qq号（这里填写的我自己的QQ号）
后显示OK，但是仍然无法在QQ中直接调用/help /status等指令（所有指令）
尝试过使用LP编辑器，但是给出的结果却是
> 无法找到QQ号
尝试回滚版本，但是每次都会再次自动更新并重启MCL
尝试使用命令交互，使自己的QQ号出现在LP编辑器中
然而，在QQ下根本就无法使用命令，何谈交互
问题已经困扰很久很久了，很多权限管理的插件都无法成功给我的主Q号赋权，除了群管插件之外，其他插件只能在控制台使用
（尝试过更改permission相关的文件，无效）
希望尽快修复这个bug，感谢！

**Comment by PeratX** [comment]
请向mirai反馈问题
