### ISSUE TITLE
W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

### ISSUE THREAD

**Issue by 0131710125q** [iTXTech/mirai-console-loader#156]
W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
请问，这个要怎么去解决

**Comment by PeratX** [comment]
请向mirai汇报问题
