### ISSUE TITLE
mirai推出了2.14版本，我使用的是mcl2.12我应该如何升级？

### ISSUE THREAD

**Issue by mlzboy** [iTXTech/mirai-console-loader#165]
mirai release的是一个源码，我应该如何操作

**Comment by xiaotong6666** [comment]
把根目录的config.json改掉

**Comment by xiaotong6666** [comment]
{
  "module_packages": [
    "mcl:org.itxtech.mcl.module.builtin"
  ],
  "mirai_repo": "https://repo.mirai.mamoe.net/keep/mcl",
  "maven_repo": [
    "https://maven.aliyun.com/repository/public"
  ],
  "packages": {
    "net.mamoe:mirai-console": {
      "channel": "maven-stable",
      "version": "2.14.0",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-console-terminal": {
      "channel": "maven-stable",
      "version": "2.14.0",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-core-all": {
      "channel": "maven-stable",
      "version": "2.14.0",
      "type": "libs",
      "versionLocked": false
    },
    "org.itxtech:mcl-addon": {
      "channel": "maven-stable",
      "version": "2.1.1",
      "type": "plugins",
      "versionLocked": false
    },
    "org.bouncycastle:bcprov-jdk15on": {
      "channel": "stable",
      "version": "1.64",
      "type": "libs",
      "versionLocked": false
    }
  },
  "archiveSuffix": [
    ".zip",
    ".mirai2.jar",
    ".mirai.jar",
    "-all.jar",
    ".jar"
  ],
  "disabled_modules": [],
  "proxy": "",
  "log_level": 1,
  "modules_props": {}
}

**Comment by xiaotong6666** [comment]
改成这样，再打开mcl就更新了
我没理解错您的意思吧

**Comment by cssxsh** [comment]
https://mirai.mamoe.net/topic/1653
