### ISSUE TITLE
关于device配置文件

### ISSUE THREAD

**Issue by RiotGamesU** [iTXTech/mirai-console-loader#18]
以前用mirai+mirai console+mirai console pure+mirai http api的时候在根目录下会生成一个device配置文件 现在用mirai console loader未找到此文件 请问现在如何配置device 不配置的话是否会出现新设备登录等问题 谢谢

**Comment by PeratX** [comment]
这个要看`mirai console`新的目录机制，1.0.0版本对目录进行了大改
