### ISSUE TITLE
MCL 支持snapshots

### ISSUE THREAD

**Issue by jerryliang122** [iTXTech/mirai-console-loader#185]
对于如何使用snapshot 的教程并不清晰。实在是不知道该如何设置

**Comment by cssxsh** [comment]
为什么要用 snapshot

**Comment by jerryliang122** [comment]
> 为什么要用 snapshot

没有为什么。就是想用MCL部署SNAPSHOT 里的MIRAI？
请问MCL支持吗？

**Comment by cssxsh** [comment]
不支持，而且 SNAPSHOT 也不稳定，他会定期清理旧版本

**Comment by jerryliang122** [comment]
好的，谢谢告知
