### ISSUE TITLE
你的帐号于22:17在一台iPad平板登录。如非本人操作，则密码可能已泄露

### ISSUE THREAD

**Issue by railannad** [iTXTech/mirai-console-loader#19]
![image](https://user-images.githubusercontent.com/36919867/102014480-31345e80-3d91-11eb-892a-2c22838fb7ac.png)

![image](https://user-images.githubusercontent.com/36919867/102014512-4f9a5a00-3d91-11eb-8283-8b2ce6e19640.png)

运行环境：CentOS8
问题描述：从登录IP来看只有这一台机子。QQ密码改过了，机子也重启过了(确保没有在screen运行两次)  ，被踢下线还是头一次遇到，哭了

**Comment by railannad** [comment]
经过多次实验，初步判断是隔壁[go cqhttp](https://github.com/Mrs4s/go-cqhttp) 登录导致bot被踢下线，但是之前从来没遇到过这种问题

**Comment by PeratX** [comment]
请向`mirai core`或者`go cqhttp`反馈，`mcl`只是个启动器
