### ISSUE TITLE
希望能添加一个可以自定义Mirai以及他附属的版本文件

### ISSUE THREAD

**Issue by DreamMiu** [iTXTech/mirai-console-loader#2]
因为插件兼容的问题，不能追求Mirai的最新版本，需要自定义一个版本

**Comment by Yiwen-Chan** [comment]
确实没发现自定义版本，不过可以手动下载，把update文件删了就不会执行更新了

**Comment by PeratX** [comment]
版本以后可以锁定


> 确实没发现自定义版本，不过可以手动下载，把update文件删了就不会执行更新了

`.\mcl --disable-script updater` 就可以实现删除updater的效果
