### ISSUE TITLE
默认repo是gitee（只有1.3.3版本）的如何切换为github（最新2.0-M1）

### ISSUE THREAD

**Issue by anaivebird** [iTXTech/mirai-console-loader#20]
gitee仓库的mirai-core-all还是1.3.3版本，github已经更新为2.0-M1

切换为github应该什么地址

mcl -m https://raw.githubusercontent.com/mamoe/mirai/master
报错
02:14:29 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.net.ConnectException (updater.js#57)

**Comment by PeratX** [comment]
已经添加2.0系列版本
