### ISSUE TITLE
启动报错 NoSuchMethodError

### ISSUE THREAD

**Issue by LeSnow-Ye** [iTXTech/mirai-console-loader#21]
实在是没弄好....求教

![image](https://user-images.githubusercontent.com/40481418/102692836-13fc0600-4251-11eb-9d53-f220ab38b6fb.png)

![image](https://user-images.githubusercontent.com/40481418/102692818-eadb7580-4250-11eb-9f75-314164c3a028.png)

**Comment by PeratX** [comment]
`.\mcl --update-package net.mamoe:mirai-core-all --channel nightly`
讲频道切换到`nightly`或者`beta`才能收到更新
