### ISSUE TITLE
求助启动器报错

### ISSUE THREAD

**Issue by Sknp1006** [iTXTech/mirai-console-loader#25]
在java11条件下，centos8、windows、Ubuntu-20.04 WSL2均出现以下错误，只有当mirai-console为1.1.0版本时能正常运行，但是按照mirai的issues提到的无法登录问题，在console2.0-M1-1上才得到解决，请问如何才能正常使用？

`PS C:\Users\74001\Desktop\mcl-1.0.3> ./mcl                                                                                                                                                                                                    01:23:49 [INFO] Mirai Console Loader version 1.0.3-6e34f43                                                                                                                                                                                   01:23:49 [INFO] https://github.com/iTXTech/mirai-console-loader                                                                                                                                                                              01:23:49 [INFO] This program is licensed under GNU AGPL v3                                                                                                                                                                                   01:23:49 [DEBUG] Loading script: boot.js                                                                                                                                                                                                     01:23:49 [DEBUG] Loading script: config.js                                                                                                                                                                                                   01:23:49 [DEBUG] Loading script: repo.js                                                                                                                                                                                                     01:23:49 [DEBUG] Loading script: updater.js                                                                                                                                                                                                  01:23:50 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M1-1                                                                                                                                                                         01:23:50 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M1-1                                                                                                                                                                01:23:50 [INFO] Verifying "net.mamoe:mirai-core-all" version 1.3.3                                                                                                                                                                          java.lang.NoSuchMethodError: net.mamoe.mirai.utils.MiraiLogger$Companion.setDefaultLoggerCreator(Lkotlin/jvm/functions/Function1;)V                                                                                                                  at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.<clinit>(MiraiConsoleImplementationBridge.kt:99)                                                                                                                        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)                                                                                                                                     at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)                                                                                                                              at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)                                                                                                                      at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)                                                                                                                                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                  at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                                                                at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)                                                                                                                                                                                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                  at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                                                                at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)                                                                                                                                                                               at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)                                                                                                                                                                   at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)                                                                                                                                                                   at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)                                                                                                                                                                       at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)                                                                                                                                                             at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)                                                                                                                                                                  at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)                                                                                                                                                                   at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)                                                                                                                                                             at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)                                                                                                                                                                          at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)                                                                                                                                                             at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)                                                                                                                                                        at org.mozilla.javascript.Context.call(Context.java:554)                                                                                                                                                                                     at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)                                                                                                                                                                       at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)                                                                                                                                                                 at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)                                                                                                                                                             at com.sun.proxy.$Proxy4.run(Unknown Source)                                                                                                                                                                                                 at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)                                                                                                                                                                    at org.itxtech.mcl.Loader.start(Loader.java:128)                                                                                                                                                                                             at org.itxtech.mcl.Loader.main(Loader.java:53)                                                                                                                                                                                       java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.console.MiraiConsole                                                                                                                                                      at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:218)                                                                                                                                     at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)                                                                                                                              at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)                                                                                                                      at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)                                                                                                                                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                  at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                                                                at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)                                                                                                                                                                                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                  at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                                                                at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)                                                                                                                                                                               at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)                                                                                                                                                                   at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)                                                                                                                                                                   at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)                                                                                                                                                                       at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)                                                                                                                                                             at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)                                                                                                                                                                  at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)                                                                                                                                                                   at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)                                                                                                                                                             at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)                                                                                                                                                                          at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)                                                                                                                                                             at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)                                                                                                                                                        at org.mozilla.javascript.Context.call(Context.java:554)                                                                                                                                                                                     at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)                                                                                                                                                                       at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)                                                                                                                                                                 at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)                                                                                                                                                             at com.sun.proxy.$Proxy4.run(Unknown Source)                                                                                                                                                                                                 at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)                                                                                                                                                                    at org.itxtech.mcl.Loader.start(Loader.java:128)                                                                                                                                                                                             at org.itxtech.mcl.Loader.main(Loader.java:53)                                                                                                                         `

**Comment by SnowMoonSS** [comment]
https://github.com/iTXTech/mirai-console-loader/issues/24
参考这个

**Comment by Sknp1006** [comment]
> #23
> 参考这个

非常感谢，可以运行了 :D
