### ISSUE TITLE
macOS上运行一段时间后进程Loader占用大量CPU资源

### ISSUE THREAD

**Issue by 45gfg9** [iTXTech/mirai-console-loader#3]
Java 版本15

<img width="559" alt="截屏2020-10-15 22 00 22" src="https://user-images.githubusercontent.com/37043529/96139850-d5d12600-0f31-11eb-8158-5ea4f67f9cda.png">

**Comment by PeratX** [comment]
loader在启动`mirai console`之后进入阻塞, 没有任何后台线程,且该进程为`mirai console`的运行进程, 考虑占用是`mirai`本身的行为

**Comment by PeratX** [comment]
同时可以尝试不用`loader`启动并观察`mirai console`的占用情况

**Comment by 45gfg9** [comment]
按照mirai-console文档(https://github.com/mamoe/mirai-console/blob/master/docs/Run.md)运行了几天，没有出现占用CPU的情况
也没有Loader进程
