### ISSUE TITLE
BUG:更新后未删除旧插件导致重加载报错退出

### ISSUE THREAD

**Issue by GiGaFotress** [iTXTech/mirai-console-loader#34]
使用的是mcl自带插件中心的mirai-native，更新后报错
mirai-native is already loaded and cannot be reloaded
查看plguins内同时存在mirai-native 196和195，导致启动失败，日志与文件均已经删除暂无法提供相关日志与截图

**Comment by PeratX** [comment]
mcl 1.0.3已经修复该情况，要求是通过mcl检查到的更新会自动重命名旧版本插件
