### ISSUE TITLE
chat-command 插件的使用方法

### ISSUE THREAD

**Issue by AdorableParker** [iTXTech/mirai-console-loader#35]
按道理，chat-command 插件只是之前的聊天命令功能独立插件化了，安装上就和之前一样的运行吧。
为什么我这边MCL安装上chat-command 之后没效果呢，也执行过了授权命令。
```
> /permission pp *
net.mamoe.mirai.console.chat-command:*
```

**Comment by PeratX** [comment]
确实，chat-command的发布出现了问题，导致新版本没发布上去

**Comment by PeratX** [comment]
检查了一下，现在已经上去了，详见
https://bintray.com/him188moe/mirai/chat-command
如果还有问题，请贴出日志。

**Comment by AdorableParker** [comment]
这个是安装 chat-command 时的控制台日志
```
jetpi@LAPTOP-AQ265AJH -> D:\..\..\mcl-1.0.3 -> ./mcl --update-package net.mamoe:chat-command --type plugin --channel stable
 22:21:49 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 22:21:49 [INFO] https://github.com/iTXTech/mirai-console-loader
 22:21:49 [INFO] This program is licensed under GNU AGPL v3
 22:21:49 [DEBUG] Loading script: boot.js
 22:21:49 [DEBUG] Loading script: config.js
 22:21:49 [DEBUG] Loading script: repo.js
 22:21:49 [DEBUG] Loading script: updater.js
 22:21:49 [INFO] Package "net.mamoe:chat-command" has been added.
jetpi@LAPTOP-AQ265AJH -> D:\..\..\mcl-1.0.3 -> .\mcl
 22:21:53 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 22:21:53 [INFO] https://github.com/iTXTech/mirai-console-loader
 22:21:53 [INFO] This program is licensed under GNU AGPL v3
 22:21:53 [DEBUG] Loading script: boot.js
 22:21:53 [DEBUG] Loading script: config.js
 22:21:53 [DEBUG] Loading script: repo.js
 22:21:53 [DEBUG] Loading script: updater.js
 22:21:53 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M2-1-dev-1
 22:21:54 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M2-1-dev-1
 22:21:54 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0-M2-2
 22:21:54 [INFO] Verifying "net.mamoe:chat-command" version
 22:21:54 [INFO] "net.mamoe:chat-command:" is corrupted. Start downloading...
 Downloading chat-command-0.3.0.jar [==============================] 11.25 KB
 Downloading chat-command-0.3.0.sha1 [==============================] 40 B
 Downloading chat-command-0.3.0.metadata [==============================] 236 B
 22:21:56 [WARNING] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-M2-dev-14. Current version is 2.0-M2-1-dev-1
```
我期望安装后的效果是这样的(MiraiOK-M4 运行效果，这个版本还没把聊天环境命令触发独立出去)
```
2021-01-03 22:54:00 V/Bot 2951899724: [测试用群(580695689)] Parker(1514880969) -> [mirai:source:4516,-501935749]/help
2021-01-03 22:54:01 V/Bot 2951899724: Group(580695689) <- 
◆ Command list
/help
◆ Log in a bot account.
/login <id> <password>
◆ Manage permissions
/permission cancel <target> <permission>
/permission cancelall <target> <permission>
/permission listpermissions
/permission permit <target> <permission>
/permission permittedpermissions <target>
◆ Stop the whole world.\n/stop
```
实际效果是不做反应，这个MCL是的控制台日志
```
2021-01-03 22:42:12 V/Bot.963795439: [测试用群(580695689)] Parker(1514880969) -> [mirai:source:[4513],[-1162668308]]/help
2021-01-03 22:49:09 I/Bot.963795439: Connection lost, retrying login
2021-01-03 22:49:09 I/Bot.963795439: Online OtherClients:
2021-01-03 22:49:09 I/Bot.963795439: Reconnected successfully in 0.749s
```
我怀疑是否于上面安装时的警告`[WARNING] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-M2-dev-14. Current version is 2.0-M2-1-dev-1`有关，并且想知道如何才能在聊天环境触发命令

**Comment by BohrX** [comment]
> 这个是安装 chat-command 时的控制台日志
> 
> ```
> jetpi@LAPTOP-AQ265AJH -> D:\..\..\mcl-1.0.3 -> ./mcl --update-package net.mamoe:chat-command --type plugin --channel stable
>  22:21:49 [INFO] Mirai Console Loader version 1.0.3-6e34f43
>  22:21:49 [INFO] https://github.com/iTXTech/mirai-console-loader
>  22:21:49 [INFO] This program is licensed under GNU AGPL v3
>  22:21:49 [DEBUG] Loading script: boot.js
>  22:21:49 [DEBUG] Loading script: config.js
>  22:21:49 [DEBUG] Loading script: repo.js
>  22:21:49 [DEBUG] Loading script: updater.js
>  22:21:49 [INFO] Package "net.mamoe:chat-command" has been added.
> jetpi@LAPTOP-AQ265AJH -> D:\..\..\mcl-1.0.3 -> .\mcl
>  22:21:53 [INFO] Mirai Console Loader version 1.0.3-6e34f43
>  22:21:53 [INFO] https://github.com/iTXTech/mirai-console-loader
>  22:21:53 [INFO] This program is licensed under GNU AGPL v3
>  22:21:53 [DEBUG] Loading script: boot.js
>  22:21:53 [DEBUG] Loading script: config.js
>  22:21:53 [DEBUG] Loading script: repo.js
>  22:21:53 [DEBUG] Loading script: updater.js
>  22:21:53 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M2-1-dev-1
>  22:21:54 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M2-1-dev-1
>  22:21:54 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0-M2-2
>  22:21:54 [INFO] Verifying "net.mamoe:chat-command" version
>  22:21:54 [INFO] "net.mamoe:chat-command:" is corrupted. Start downloading...
>  Downloading chat-command-0.3.0.jar [==============================] 11.25 KB
>  Downloading chat-command-0.3.0.sha1 [==============================] 40 B
>  Downloading chat-command-0.3.0.metadata [==============================] 236 B
>  22:21:56 [WARNING] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-M2-dev-14. Current version is 2.0-M2-1-dev-1
> ```
> 
> 我期望安装后的效果是这样的(MiraiOK-M4 运行效果，这个版本还没把聊天环境命令触发独立出去)
> 
> ```
> 2021-01-03 22:54:00 V/Bot 2951899724: [测试用群(580695689)] Parker(1514880969) -> [mirai:source:4516,-501935749]/help
> 2021-01-03 22:54:01 V/Bot 2951899724: Group(580695689) <- 
> ◆ Command list
> /help
> ◆ Log in a bot account.
> /login <id> <password>
> ◆ Manage permissions
> /permission cancel <target> <permission>
> /permission cancelall <target> <permission>
> /permission listpermissions
> /permission permit <target> <permission>
> /permission permittedpermissions <target>
> ◆ Stop the whole world.\n/stop
> ```
> 
> 实际效果是不做反应，这个MCL是的控制台日志
> 
> ```
> 2021-01-03 22:42:12 V/Bot.963795439: [测试用群(580695689)] Parker(1514880969) -> [mirai:source:[4513],[-1162668308]]/help
> 2021-01-03 22:49:09 I/Bot.963795439: Connection lost, retrying login
> 2021-01-03 22:49:09 I/Bot.963795439: Online OtherClients:
> 2021-01-03 22:49:09 I/Bot.963795439: Reconnected successfully in 0.749s
> ```
> 
> 我怀疑是否于上面安装时的警告`[WARNING] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-M2-dev-14. Current version is 2.0-M2-1-dev-1`有关，并且想知道如何才能在聊天环境触发命令

同样无效
