### ISSUE TITLE
更改默认config.json

### ISSUE THREAD

**Issue by Nambers** [iTXTech/mirai-console-loader#40]
能不能更改默认的config.json到issue#26里那样，因为现在默认的大多数人用好像都会报错

**Comment by Nambers** [comment]
改成类似这种  https://github.com/iTXTech/mirai-console-loader/issues/26#issuecomment-750437011

**Comment by PeratX** [comment]
有道理，应该全部nightly把

**Comment by Nambers** [comment]
> 有道理，应该全部nightly把

嗯 确实
