### ISSUE TITLE
MCL 的连接问题

### ISSUE THREAD

**Issue by WindLeaf233** [iTXTech/mirai-console-loader#44]
mcl 经常会时不时的显示：Connection lost, retrying login。
Reconnect 之后，就无法接收消息了，只能重新启动或者 login。
有时候还会被 Connection lost, retrying login 的消息刷屏。

请问为什么会丢失连接？是服务器不稳定吗还是什么原因？

**Comment by PeratX** [comment]
这个应该反馈给mirai，mirai console启动之后，mcl的工作就完成了
