### ISSUE TITLE
执行发生错误

### ISSUE THREAD

**Issue by aion1998** [iTXTech/mirai-console-loader#47]
不是很懂java，这报错是啥意思，缺少啥东西吗，我是直接下载release的

![image](https://user-images.githubusercontent.com/19725014/105974093-7eae2600-60c8-11eb-95e2-568b882278b9.png)

**Comment by PeratX** [comment]
需要使用JDK 11，可以从https://adoptopenjdk.net/下载

**Comment by aion1998** [comment]
、、、我就是JDK11



&nbsp;-新田月会
&nbsp;-君宁天下
&nbsp;-新细胞
&nbsp;-古科学部
&nbsp;-尖端技术局
&nbsp;&nbsp;新田-宁骑


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iTXTech/mirai-console-loader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 晚上8:52
收件人:&nbsp;"iTXTech/mirai-console-loader"<mirai-console-loader@noreply.github.com&gt;;
抄送:&nbsp;"刘宁"<1075858260@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iTXTech/mirai-console-loader] 执行发生错误 (#47)





 
需要使用JDK 11，可以从https://adoptopenjdk.net/ 下载

**Comment by aion1998** [comment]
> 需要使用JDK 11，可以从https://adoptopenjdk.net/ 下载

感谢，我还以为说的是java啥的

**Comment by zxin8580** [comment]
感谢！
