### ISSUE TITLE
不知道是什么情况的报错

### ISSUE THREAD

**Issue by user670** [iTXTech/mirai-console-loader#48]
![image](https://user-images.githubusercontent.com/22617255/105992850-8ed1ff80-60e0-11eb-84b3-3bd25e650e2c.png)
在自己的电脑上运行正常，但是在我的服务器上运行出现这个错误，不知道是什么导致的

**Comment by PeratX** [comment]
请检查最新版是否仍然出现此报错

**Comment by PeratX** [comment]
包的pack类型为空，请检查配置文件。
