### ISSUE TITLE
更新下载超时问题

### ISSUE THREAD

**Issue by 1135890950** [iTXTech/mirai-console-loader#52]
挂国内的服务器，更新下载的时候比较慢，但是是有速度的，我这里的一些插件下载大概要5分钟！但mcl更新下载大概到两三分钟（大概时间，我没掐表算过）的时候就会超时！虽然有办法解决但是体验不好，希望这方面能有所改进！

**Comment by PeratX** [comment]
检查了下代码，下载的时候没有设置超时

**Comment by 1135890950** [comment]
> 检查了下代码，下载的时候没有设置超时

啊？我的错，当时想当然以为是下载超时的问题，就懒没截图报错信息！现在换了服务器，一时半会也复现不了

**Comment by PeratX** [comment]
emmm那就等复现了再打开吧
