### ISSUE TITLE
用不了mcl指令

### ISSUE THREAD

**Issue by MCBBS-Pro** [iTXTech/mirai-console-loader#57]
![屏幕截图 2021-02-14 013135](https://user-images.githubusercontent.com/65444745/107856665-9e817000-6e64-11eb-94a3-0e54b4b1a2b0.png)
难道是因为没用idea?

**Comment by PeratX** [comment]
启动之后就是mirai console了，没有mcl指令的。
如果要用mcl指令，应该在cmd里面用
