### ISSUE TITLE
提问 关于插件外置依赖库

### ISSUE THREAD

**Issue by FxRayHughes** [iTXTech/mirai-console-loader#58]
如果我的插件使用了外置依赖库 该用什么方式在启动mcl的时候也加载所需依赖库呢?

**Comment by PeratX** [comment]
比如说？您是想要实现什么操作？

**Comment by PeratX** [comment]
不活跃的issue，暂时关闭。

**Comment by FxRayHughes** [comment]
> 比如说？您是想要实现什么操作？

我想让我的插件使用谷歌的一个工具包来调用和控制yaml
