### ISSUE TITLE
问题: 如何添加插件

### ISSUE THREAD

**Issue by Tomyail** [iTXTech/mirai-console-loader#6]
按照自己的理解把插件的 jar 包放到 plugins 文件夹下:

![image](https://user-images.githubusercontent.com/350722/97520549-74e82a00-19d6-11eb-9287-30fb52164490.png)

之后启动 mcl:
![image](https://user-images.githubusercontent.com/350722/97520521-67cb3b00-19d6-11eb-8538-22cc55862266.png)

提示没有发现任何插件? 请问我是不是错过了什么..

**Comment by xilou31** [comment]
请问问题解决了吗？我也遇到同样问题了。不知道怎么添加插件。

**Comment by PeratX** [comment]
需要新版插件，支持mirai-console 1.0的
