### ISSUE TITLE
支持jitpack |  多maven repo支持

### ISSUE THREAD

**Issue by Itsusinn** [iTXTech/mirai-console-loader#60]
jitpack是一个Maven Repo
在jitpack发包十分容易（相比与maven central
https://jitpack.io/

**Comment by PeratX** [comment]
多maven repo计划中，jitpack好像没看到国内镜像，请问是否有国内镜像？

**Comment by Itsusinn** [comment]
> 多maven repo计划中，jitpack好像没看到国内镜像，请问是否有国内镜像？

无国内镜像
