### ISSUE TITLE
release包中macos脚本文件不对

### ISSUE THREAD

**Issue by leonsux** [iTXTech/mirai-console-loader#62]
![image](https://user-images.githubusercontent.com/16915485/109667175-d7cb1700-7baa-11eb-85c2-4a8e13ad0b1d.png)

下图是 `mcl-1.0.5.zip`，`mcl` 无法执行

![image](https://user-images.githubusercontent.com/16915485/109667505-2d072880-7bab-11eb-9ab7-1834e2ccbb89.png)

下图是 `Source code.(zip)`，`mcl` 可执行，但缺少 `mcl.jar`

![image](https://user-images.githubusercontent.com/16915485/109667728-650e6b80-7bab-11eb-87c6-5ae7c4f39729.png)

最终把  `Source code.(zip)` 里的 `mcl` 放到  `mcl-1.0.5.zip` 里就可以了

![image](https://user-images.githubusercontent.com/16915485/109667872-8cfdcf00-7bab-11eb-8f6d-a850b99bdc30.png)

**Comment by PeratX** [comment]
*nix系统需要自行执行 chmox +x mcl才行，zip格式可能不支持添加unix文件属性
