### ISSUE TITLE
如何安装 mirai-api-http 1.10.0？

### ISSUE THREAD

**Issue by Drincann** [iTXTech/mirai-console-loader#65]
指定版本后安装的还是 1.9.8

```shell
.\mcl --update-package net.mamoe:mirai-api-http --version 1.10.0
```
out
>  18:13:47 [INFO] iTXTech Mirai Console Loader version 1.0.4-b4213ea
 18:13:47 [INFO] https://github.com/iTXTech/mirai-console-loader
 18:13:47 [INFO] This program is licensed under GNU AGPL v3
 18:13:47 [DEBUG] Loading script: announcement.js
 18:13:47 [DEBUG] Loading script: boot.js
 18:13:47 [DEBUG] Loading script: config.js
 18:13:47 [DEBUG] Loading script: repo.js
 18:13:47 [DEBUG] Loading script: updater.js
 18:13:47 [INFO] Package "net.mamoe:mirai-api-http" has been updated.

启动 mcl

out
> 18:14:51 [INFO] "net.mamoe:mirai-api-http:1.10.0" is corrupted. Start downloading...
 Downloading mirai-api-http-1.9.8.jar [==============================] 4.89 MB
 Downloading mirai-api-http-1.9.8.sha1 [==============================] 40 B
 Downloading mirai-api-http-1.9.8.metadata [==============================] 531 B

我需要更换 channel 吗？

顺便问一波 channel 具体指什么，如何知道一个包有哪些 channel？

**Comment by PeratX** [comment]
.\mcl -j 可以查看所有包
.\mcl -i net.mamoe:mirai-api-http可以查看所有版本

**Comment by PeratX** [comment]
现在应该有1.10.0了

**Comment by Drincann** [comment]
> .\mcl -j 可以查看所有包
> .\mcl -i net.mamoe:mirai-api-http可以查看所有版本

感谢
