### ISSUE TITLE
运行一段时间之后 cpu占用过高

### ISSUE THREAD

**Issue by LinHui88** [iTXTech/mirai-console-loader#66]
rt 不知是本加载器的问题还是mcl自身的问题
![Z)~GY3J2P9RBHO6_U3KYDTK](https://user-images.githubusercontent.com/40729083/113534114-b4ace080-960a-11eb-91d1-1d1f4a851ad7.png)
![VYEX8VMP56ITFN9)B K{YKA](https://user-images.githubusercontent.com/40729083/113534120-b7a7d100-960a-11eb-8dfb-325f9f7ef290.png)

**Comment by dousha** [comment]
已知这个问题来自 mirai 本身，不知道在新版本中有没有修复。

**Comment by PeratX** [comment]
mirai 本身的问题，请向mirai汇报
