### ISSUE TITLE
为什么项目运行成功了端口无法访问

### ISSUE THREAD

**Issue by sunday960126** [iTXTech/mirai-console-loader#72]
<img width="942" alt="图片" src="https://user-images.githubusercontent.com/38512781/120930866-b33e8800-c721-11eb-843b-951b81bb5d81.png">
<img width="363" alt="图片" src="https://user-images.githubusercontent.com/38512781/120930901-d49f7400-c721-11eb-82a2-e5a8bdb076fc.png">

**Comment by PeratX** [comment]
请反馈到相关项目
