### ISSUE TITLE
mirai-api-http未更新

### ISSUE THREAD

**Issue by HinataKato** [iTXTech/mirai-console-loader#75]
mirai-api-http 未更新至 2.0.2 版本

看起来是
https://github.com/project-mirai/mirai-repo-mirror
没更

**Comment by PeratX** [comment]
应该更新了

**Comment by HinataKato** [comment]
> 应该更新了

并没有 还是1.10.0

**Comment by PeratX** [comment]
该项目维护者迟迟没有将版本发布到maven central

**Comment by Hu-Wentao** [comment]
> 该项目维护者迟迟没有将版本发布到maven central

如何通过mcl下载最新的mirai-api-http? 只能手动下载jar吗?

**Comment by HinataKato** [comment]
> > 该项目维护者迟迟没有将版本发布到maven central
> 
> 如何通过mcl下载最新的mirai-api-http? 只能手动下载jar吗?

是的
