### ISSUE TITLE
使用./mcl启动mcl时报错

### ISSUE THREAD

**Issue by Shinya754** [iTXTech/mirai-console-loader#78]
按照指引安装了mcl后，使用./mcl指令启动mcl时报错：
`[ERROR] javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
截图如下：
![image](https://user-images.githubusercontent.com/43848947/126111561-0dac6d5f-cdb4-421b-bbb2-d7630577d51d.png)

我的jdk版本是16.0.1
![image](https://user-images.githubusercontent.com/43848947/126111652-2d1da49b-fc50-424f-b4d7-f58a3a82e7fc.png)

请问这可能是什么导致的错误？为了解决这个问题我还应该提供哪些信息？

**Comment by PeratX** [comment]
JDK16未经测试，请尝试使用JDK11 LTS

**Comment by PeratX** [comment]
https://stackoverflow.com/questions/18378869/pkix-path-building-failed-in-java-application

**Comment by Shinya754** [comment]
> https://stackoverflow.com/questions/18378869/pkix-path-building-failed-in-java-application

您好，根据您的提示，我将jdk版本换成了11.0.11，并且定位到了问题是由于我的环境中没有添加对应的证书/对证书不信任导致的，但是我无法根据powershell中给出的报错信息得出mcl下载"org.bouncycastle:bcprov-jdk15on:1.64"的地址，请问我应该添加对哪个网站的信任证书呢

**Comment by PeratX** [comment]
查看config.json中的信息，应该是maven.aliyun.com
