### ISSUE TITLE
MCL 无法正常启动，但是无错误提示

### ISSUE THREAD

**Issue by Slontia** [iTXTech/mirai-console-loader#94]
操作系统：CentOS Linux release 8.0.1905 (Core)
二进制 md5：aa6c55d2c1db7d17d8715057feceeb95（和当前 master 分支 md5 一致，应该是最新版本）
Java 版本：
```
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1-LTS, mixed mode, sharing)
```
运行 mcl 日志：
![image](https://user-images.githubusercontent.com/24265849/150783269-ab537868-2deb-479d-8639-fbf28eaacfb5.png)
mcl 无法启动，但是没有任何报错信息

这套环境之前启动是没问题的，挂了几天后，刚刚退出重启，结果就报了上图里的这些日志信息，没有启动成功

**Comment by PeratX** [comment]
上传下config.json看看

**Comment by Slontia** [comment]
重装了下 mcl，已经解决了，十分感谢🙏
