### ISSUE TITLE
GitHub源无法使用

### ISSUE THREAD

**Issue by Cicini** [iTXTech/mirai-console-loader#95]
无论是手动修改`config.json`还是通过
`java -jar mcl.jar --set-mirai-repo https://github.com/project-mirai/mirai-repo-mirror`
修改均报错
`[ERROR] TypeError: Cannot call method "containsKey" of null`
由于我的服务器(海外)突然没法连上Gitee(提示网络错误)，所以准备修改为GitHub源，发现无法正常使用(目前MCL也无法正常启动).

**Comment by Cicini** [comment]
实在是没找到相关说明(

**Comment by Cicini** [comment]
使用`https://raw.githubusercontent.com/project-mirai/mirai-repo-mirror/master/`
会出现报错
`[ERROR] java.net.ConnectException`

**Comment by Cicini** [comment]
确认了( 是连不上maven的报错，github的填写`https://raw.githubusercontent.com/project-mirai/mirai-repo-mirror/master/`就能用了

**Comment by PeratX** [comment]
![~BR0O{S)(N3E}L1$_CZ3HYI](https://user-images.githubusercontent.com/13656668/151650167-632b5e3c-6d1e-4063-9ac3-0eeb5eecb654.jpg)

**Comment by Cicini** [comment]
> ![~BR0O{S)(N3E}L1$_CZ3HYI](https://user-images.githubusercontent.com/13656668/151650167-632b5e3c-6d1e-4063-9ac3-0eeb5eecb654.jpg)
![QQ图片20220129142457](https://user-images.githubusercontent.com/62730438/151650262-93f07d11-f8c8-43e7-aa0f-523a5b79d5b8.png)

**Comment by GongT** [comment]
做个笔记（

```bash
local DATA
DATA=$(<"config.json")
DATA=$(echo "$DATA" | jq --arg URL "https://raw.githubusercontent.com/project-mirai/mirai-repo-mirror/master" '.mirai_repo = $URL')
DATA=$(echo "$DATA" | jq --arg URL "https://repo1.maven.org/maven2" '.maven_repo = [$URL]')
DATA=$(echo "$DATA" | jq '.disabled_modules = ["announcement"]')
echo "$DATA" >"config.json"
```

**Comment by SekiBetu** [comment]
> 做个笔记（
> 
> ```shell
> local DATA
> DATA=$(<"config.json")
> DATA=$(echo "$DATA" | jq --arg URL "https://raw.githubusercontent.com/project-mirai/mirai-repo-mirror/master" '.mirai_repo = $URL')
> DATA=$(echo "$DATA" | jq --arg URL "https://repo1.maven.org/maven2" '.maven_repo = [$URL]')
> DATA=$(echo "$DATA" | jq '.disabled_modules = ["announcement"]')
> echo "$DATA" >"config.json"
> ```

这项目对国外服务器不太友好，默认就是国内源，下半天，我也是改了几次都失败，按这个改没问题了

**Comment by Cicini** [comment]
> 

其实直接手动把config里面的地址修改一下就可以了(

**Comment by SekiBetu** [comment]
> > 
> 
> 其实直接手动把config里面的地址修改一下就可以了(

说明里给的地址是错误的，直接报错

**Comment by GongT** [comment]
> 其实直接手动把config里面的地址修改一下就可以了(

整脚本是因为我同时在本地和github action上用（

这项目文档确实一直不多，对新手不太友好，熟悉了就好了（
